name: Checks

on:
  push:
  pull_request:

jobs:
  check-format:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: CI/check_format .
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: changed
          path: changed
