name: Checks

on:
  push:
  pull_request:

jobs:
  check-format:
    name: Check Code Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies with clang
        run: |
          apt install clang -y

      - name: Check Format
        shell: bash
        run: source ./CI/check_format.sh .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: changed
          path: changed
