name: Checks

on:
  pull_request:

jobs:
  check-format:
    name: Check Code Format
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies for clang
        run: |
          clang --version

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Format
        shell: bash
        run: |
          source ./.CI/check_format.sh .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: DataVisualizerFormatted
          path: DataVisualizerFormatted
