name: Package Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container: 
      image: rootproject/root:latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu_GCC",
            os: ubuntu-latest,
            cc: "gcc-10",
            cxx: "g++-10",
          }
        - {
            name: "Ubuntu_CLANG",
            os: ubuntu-latest,
            cc: "clang-13",
            cxx: "clang++-13",
          }

    steps:
      - name: Install common dependencies
        run: |
          #apt update
          #apt install libcppunit-dev cmake -y
          cmake --version
      - name: Install dependencies on ubuntu with gcc
        if: startsWith(matrix.config.name, 'Ubuntu_GCC')
        run: |
          #apt install ${{ matrix.config.cc }} -y
          #apt install ${{ matrix.config.cxx }} -y
          ${{ matrix.config.cc }} --version
          ${{ matrix.config.cxx }} --version
      - name: Install dependencies on ubuntu with clang
        if: startsWith(matrix.config.name, 'Ubuntu_CLANG')
        run: |
          #apt install ${{ matrix.config.cc }} -y
          ${{ matrix.config.cc }} --version
      - name: Check ROOT version
        run: |
          root --version

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the compilation
      - name: Prepare folders
        run: |
          mkdir build
      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_CXX_FLAGS="-Werror -Wall" -DCMAKE_CXX_STANDARD="17" -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 
      - name: Install
        run: |
          cmake --build build
