name: Package Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container:
      image: rootproject/root:latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu_GCC",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-10",
            cxx: "g++-10",
          }
        - {
            name: "Ubuntu_CLANG",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-11",
            cxx: "clang++-11",
          }

    steps:
      - name: Install common dependencies
        run: |
          apt update
          apt install libcppunit-dev cmake -y
          cmake --version
      - name: Install dependencies on ubuntu with gcc
        if: startsWith(matrix.config.name, 'Ubuntu_GCC')
        run: |
          gcc --version
      - name: Install dependencies on ubuntu with clang
        if: startsWith(matrix.config.name, 'Ubuntu_CLANG')
        run: |
          #apt install clang-11 -y
          clang-11 --version


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the compilation
      - name: Run the compilation 
        run: >
          mkdir build
          cmake -S . -B build
          -DCMAKE_CXX_FLAGS=-Werror
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} 
          -DCMAKE_C_COMPILER=-DCMAKE_CXX_COMPILER=${{ matrix.config.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 
          cmake --build build
