name: Package Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container: 
      image: rootproject/root:6.22.08-fedora34
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "CI-build-GCC",
            os: ubuntu-20.04,
            cc: "gcc",
            cxx: "g++",
          }
        - {
            name: "CI-build-CLANG",
            os: ubuntu-20.04,
            cc: "clang",
            cxx: "clang++",
          }

    steps:
      - name: Install common dependencies
        run: |
          cmake --version
      - name: Install dependencies with gcc
        if: startsWith(matrix.config.name, 'CI-build-GCC')
        run: |
          ${{ matrix.config.cc }} --version
          ${{ matrix.config.cxx }} --version
      - name: Install dependencies with clang
        if: startsWith(matrix.config.name, 'CI-build-CLANG')
        run: |
          dnf install ${{ matrix.config.cc }} -y
          ${{ matrix.config.cc }} --version
      - name: Check ROOT version
        run: |
          root --version

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the compilation
      - name: Prepare folders
        run: |
          mkdir build
      - name: Build with gcc
        if: startsWith(matrix.config.name, 'CI-build-GCC')
        run: >
          cmake -S . -B build 
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }} 
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
      - name: Build with gcc
        if: startsWith(matrix.config.name, 'CI-build-CLANG')
        run: >
          cmake -S . -B build 
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }} 
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -DCMAKE_CXX_FLAGS="-Qunused-arguments"
      - name: Install
        run: |
          cmake --build build
