name: Package Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container:
      image: rootproject/root:6.24.06-conda
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Macos_GCC",
            os: macos-11,
            build_type: "Release",
            cc: "gcc-9",
            cxx: "g++-9",
          }
        - {
            name: "Macos_CLANG",
            os: macos-11,
            build_type: "Release",
            cc: "clang-11",
            cxx: "clang++-11",
          }

    steps:
      - name: Install common dependencies
        run: |
          apt update
          #apt install libcppunit-dev cmake -y
          cmake --version
      - name: Install dependencies on ubuntu with gcc
        if: startsWith(matrix.config.name, 'Macos_GCC')
        run: |
          apt install ${{ matrix.config.cc }} -y
          apt install ${{ matrix.config.cxx }} -y
          ${{ matrix.config.cc }} --version
          ${{ matrix.config.cxx }} --version
      - name: Install dependencies on ubuntu with clang
        if: startsWith(matrix.config.name, 'Macos_CLANG')
        run: |
          apt install ${{ matrix.config.cc }} -y
          ${{ matrix.config.cc }} --version

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the compilation
      - name: Run the compilation 
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 
          cmake --build build
