name: Package Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container: 
      image: rootproject/root:6.22.08-fedora34
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu_GCC",
            os: ubuntu-20.04,
            cc: "gcc-11",
            cxx: "g++-11",
          }
        - {
            name: "Ubuntu_CLANG",
            os: ubuntu-20.04,
            cc: "clang-12",
            cxx: "clang++-12",
          }

    steps:
      - name: Install common dependencies
        run: |
          #dnf upgrade
          #dnf install libcppunit-dev cmake
          cmake --version
          gcc --version

      - name: Check ROOT version
        run: |
          root --version

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the compilation
      - name: Prepare folders
        run: |
          mkdir build
      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 
      - name: Install
        run: |
          cmake --build build
